# Generated by Django 5.0.4 on 2024-05-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaynotes',
            name='uni',
            field=models.CharField(default='0fFMgN', max_length=255, unique=True),
        ),
    ]
