# Generated by Django 5.0.4 on 2024-05-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_displaynotes_uni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaynotes',
            name='uni',
            field=models.CharField(default='VeT5p8', max_length=255, unique=True),
        ),
    ]
